#user = "your_name"
#serverAddr = "9oy038ja6038.vicp.fun"
#serverAddr = "114.216.120.100"
serverAddr = "127.0.0.1"
serverPort = 7000

#loginFailExit = true
#log.to = "./frpc.log"
#log.level = "info"
#log.maxDays = 3
#log.disablePrintColor = false
auth.method = "token"
auth.token = "qazWSXERTYghh@!@#134553322(?)"
#webServer.addr = "127.0.0.1"
#webServer.port = 7400
#webServer.user = "admin"
#webServer.password = "admin"
# Admin assets directory. By default, these assets are bundled with frpc.
#webServer.assetsDir = "./static"

#webServer.pprofEnable = false
#transport.poolCount = 5
#transport.protocol = "tcp"
#transport.connectServerLocalIP = "0.0.0.0"
transport.tls.enable = true
transport.tls.certFile = "client.crt"
transport.tls.keyFile = "client.key"
#transport.tls.trustedCaFile = "ca.crt"
#transport.tls.serverName = "example.server.com"
#udpPacketSize = 1500
# 设置在frpc上启用压缩
# transport.tcpMux 为 true 时，可以启用压缩
transport.tcpMux = true

# 如果你使用的是 TCP 代理，可以参考以下示例配置
[[proxies]]
name = "tcp3389"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3389
remotePort = 13389
transport.useEncryption = true
transport.useCompression = true


